### PR TITLE
Add `addAnyHandler()`.

### PR DESCRIPTION
**Pull request by inamiy**
This pull request is a new feature for #40 to support `addAnyHandler()`
which works for both event-based & state-based transitions.

See test case: [StateMachineEventTests.swift#L382-L446](https://github.com/ReactKit/SwiftState/blob/addAnyHandler/Tests/StateMachineEventTests.swift#L382-L446)

### CODE REVIEW

**Comment by sluramod** [comment]
I expected transition to be input parameter of the method, and the handler called only when the transition happened, but regardless of how.

**Comment by inamiy** [comment]
@sluramod 
Thanks for feedback! 
That sounds even better, and I updated code in 1e88704. 
Please see updated test case.

**Comment by sluramod** [comment]
excellent, thank you.

**Comment by inamiy** [comment]
Ready to :shipit:

**Pull request merged**
