### PR TITLE
Swift 4.0 support

### PR DESCRIPTION
**Pull request by adamyanalunas**
Hi there! The current `swift/3.0` branch doesn't work on projects that target Swift 4.0. This PR is a result of running Xcode 9 migrators, cleaning up new warnings, and fixing making one value `public` instead of `internal`.

There's no `swift/4.0` branch yet so I had to target `swift/3.0`. If you create a 4.0 branch I'll change the PR's target.

### CODE REVIEW

**Comment by inamiy** [comment]
Hi @adamyanalunas , thank you for PR!

Would you mind:

- Re-target to `swift/4.0` branch
- Rename back to `_defaultOrder` (UpperCamelCase for variable name is not desirable)

By the way, Circle CI free plan is no longer available, so the change is actually not necessary.

**Comment by adamyanalunas** [comment]
@inamiy requested changes have been made.

By changing the targeted branch to `swift/4.0` there are some additional commits. I'm pretty sure that's not from my fork but let me know and I'll see if I can clean them up.

**Comment by inamiy** [comment]
@adamyanalunas 
Thank you for the fixes! Overall looks perfect 😄 
Sorry that I was pointing `swift/4.0` to wrong `swift/2.0` by mistake.
That's why additional commit is displayed in GitHub.
(I don't know why it still exists after I changed to `swift/3.0`)

Anyway, thank you for contribution, and I will merge this!
I will also invite you as collaborator, so you are free to push further commits (I can review some) or leave if you aren't interested :)

**Review by inamiy — APPROVED** [review]

**Comment by apps4everyone** [comment]
@inamiy @adamyanalunas Thank you for the fixes!

**Pull request merged**
